### ISSUE TITLE
The names of the servers would be a good to have

### ISSUE THREAD

**Issue by Shituation** [nilsstreedain/Long-List-of-DNS-Servers#1]
Right now we have IP's and we don't  know who owns them.

**Comment by nilsstreedain** [comment]
Unfortunately, the method of recording DNS responses only maps IP addresses and has no way of determining who controls it. You could perform a whois lookup to gain more information but this is not a bullet proof solution. The lists are also structured in a way to be easily read by programs so alterations that could break current formatting are unlikely. I would also like to note that this is not an exhaustive list and likely does not contain many DNS domains.
